import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { TaskStatus } from "@prisma/client";
import { RouterOutputs, api } from "@/utils/api";
import { Card } from "@/components/ui/card";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

import {
  Draggable,
  Droppable,
  DragDropContext,
  DropResult,
} from "@hello-pangea/dnd";
import { useEffect, useState } from "react";
import { Figtree } from "@next/font/google";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { z } from "zod";

type Task = RouterOutputs["tasks"]["getAll"][number];
type TaskWithIndex = Task & { index: number };

const figTree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

interface KanbanCard {
  name: string;
  color: string;
  tasks: Task[];
}

interface TaskForm {
  task?: Task;
}

export default function Home() {
  const { data } = api.tasks.getAll.useQuery();
  const [showTaskModal, setShowTaskModal] = useState(false);

  return (
    <>
      <Head>
        <title>Project Management App</title>
        <meta
          name="description"
          content="Generated by project-management-app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`grid-areas-layout grid-cols-layout grid-rows-layout grid h-full bg-white ${figTree.className}`}
      >
        <header className="grid-in-header px-3 py-2">
          <div className="flex items-center justify-between">
            <AuthShowcase />
            <Popover>
              <PopoverTrigger>
                <Button>+ New Task</Button>
              </PopoverTrigger>
              <PopoverContent>
                <TaskForm />
              </PopoverContent>
            </Popover>
          </div>
        </header>
        <div className="grid-in-main">
          <Kanban tasks={data ?? []} />
        </div>
      </main>
    </>
  );
}

const statusOptions = [
  { type: TaskStatus.BACKLOG, color: "bg-kanban-blue" },
  { type: TaskStatus.IN_PROGRESS, color: "bg-kanban-yellow" },
  { type: TaskStatus.WAITING_FOR_REVIEW, color: "bg-kanban-blue2" },
  { type: TaskStatus.DONE, color: "bg-kanban-green" },
  { type: TaskStatus.STUCK, color: "bg-kanban-red" },
];

function TaskForm(props: TaskForm) {
  const formSchema = z.object({
    name: z.string(),
    description: z.string().optional(),
    status: z.enum([
      "BACKLOG",
      "IN_PROGRESS",
      "WAITING_FOR_REVIEW",
      "DONE",
      "STUCK",
    ]),
    priority: z.enum(["HIGH", "MEDIUM", "LOW"]),
    type: z.string().optional(),
    assignee: z.string().optional(),
  });
  return <></>;
}

function TaskCard(props: TaskWithIndex) {
  return (
    <Draggable
      draggableId={`${props.id}`}
      index={props.index}
      key={props.index}
    >
      {(provided, snapshot) => (
        <Card
          ref={provided.innerRef}
          {...provided.draggableProps}
          {...provided.dragHandleProps}
          style={{
            ...provided.draggableProps.style,
            transform: `${provided.draggableProps.style?.transform ?? ""} ${snapshot.isDragging ? "rotate(3deg)" : ""}`,
          }}
          className={`mt-2 max-h-28 min-h-28 rounded-lg p-3 text-sm`}
        >
          <div className="flex justify-between font-semibold capitalize text-black">
            {props.name}
            {/* <FontAwesomeIcon icon="fa-solid fa-house" /> */}
          </div>
          <div className="mt-2 flex capitalize">
            {props.priority?.toLocaleLowerCase()}
          </div>
        </Card>
      )}
    </Draggable>
  );
}

function KanbarCard({ name, color, tasks = [] }: KanbanCard) {
  return (
    <div
      className={`max-h-screen w-64 overflow-y-hidden rounded-lg bg-kanban-grey hover:bg-kanban-grey2 hover:shadow-md`}
    >
      <div
        className={`${color} z-10 rounded-t-xl p-2 font-bold capitalize text-white`}
      >
        {name.split("_").join(" ").toLocaleLowerCase()} / {tasks?.length ?? 0}
      </div>

      <Droppable droppableId={`${name}`}>
        {(provided): JSX.Element => (
          <div
            ref={provided.innerRef}
            {...provided.droppableProps}
            className="max-h-screen min-h-60 overflow-auto px-3 pb-4 pt-1"
          >
            {tasks?.map((task, index) => {
              return <TaskCard key={task.id} index={index} {...task} />;
            })}
            {provided.placeholder}
          </div>
        )}
      </Droppable>
    </div>
  );
}

function Kanban({ tasks }: { tasks: Task[] }) {
  // const [taskData, setTaskData] = useState(tasks);
  const mutate = api.tasks.update.useMutation();

  // useEffect(() => {
  //   setTaskData(tasks);
  // }, [tasks]);

  const onDragEnd = (result: DropResult) => {
    const { source, destination, draggableId } = result;
    if (!destination) return;
    if (
      source.droppableId === destination.droppableId &&
      source.index === destination.index
    )
      return;

    mutate.mutate({
      id: parseInt(draggableId),
      status: destination.droppableId as TaskStatus,
    });
  };
  return (
    <DragDropContext onDragEnd={onDragEnd}>
      <div className="flex gap-2">
        {statusOptions.map(({ type, color }) => {
          const groupedTasks: Task[] = tasks?.filter(
            (task: Task) => task.status === type,
          );
          return (
            <KanbarCard
              key={type}
              name={type}
              color={color}
              tasks={groupedTasks}
            />
          );
        })}
      </div>
    </DragDropContext>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  return (
    <div>
      <Button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </Button>
      <p className=" text-center text-sm text-black">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
    </div>
  );
}
