import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { TaskStatus } from "@prisma/client";
import { RouterOutputs, api } from "@/utils/api";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Draggable, Droppable, DragDropContext } from "react-beautiful-dnd";

type Task = RouterOutputs["tasks"]["getAll"][number];
interface KanbanCard {
  name: string;
  color: string;
  tasks: Task[];
}

export default function Home() {
  const { data } = api.tasks.getAll.useQuery();

  const { mutate } = api.tasks.update.useMutation();

  return (
    <>
      <Head>
        <title>Project Management App</title>
        <meta
          name="description"
          content="Generated by project-management-app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <AuthShowcase />
        {/* <Button>+ New Task</Button> */}
        <Kanban tasks={data ?? []} />
      </main>
    </>
  );
}

const statusOptions = [
  { type: TaskStatus.BACKLOG, color: "bg-kanban-blue" },
  { type: TaskStatus.IN_PROGRESS, color: "bg-kanban-yellow" },
  { type: TaskStatus.WAITING_FOR_REVIEW, color: "bg-kanban-blue2" },
  { type: TaskStatus.DONE, color: "bg-kanban-green" },
  { type: TaskStatus.STUCK, color: "bg-kanban-red" },
];

function TaskCard(props: Task) {
  return (
    <Card className="mt-2 max-h-28 min-h-28 rounded-lg p-3 text-sm">
      <div className="flex justify-between font-bold capitalize text-black">
        {props.name}
      </div>
      <div className="mt-2 flex capitalize">
        {props.priority?.toLocaleLowerCase()}
      </div>
    </Card>
  );
}

function KanbarCard({ name, color, tasks = [] }: KanbanCard) {
  return (
    <div
      className={`bg-kanban-grey hover:bg-kanban-grey2 w-64 overflow-hidden rounded-lg hover:shadow-md`}
    >
      <div
        className={`${color} z-10 rounded-t-xl p-2 font-bold capitalize text-white`}
      >
        {name.split("_").join(" ").toLocaleLowerCase()} / {tasks?.length ?? 0}
      </div>

      <Droppable droppableId={`${name}`}>
        {(provided): JSX.Element => (
          <div
            {...provided.droppableProps}
            ref={provided.innerRef}
            className="min-h-60 overflow-auto px-3 pb-4 pt-1"
          >
            {tasks?.map((task) => {
              return <TaskCard key={task.id} {...task} />;
            })}
          </div>
        )}
      </Droppable>
    </div>
  );
}

function Kanban({ tasks }: { tasks: Task[] }) {
  const onDragEnd = () => {
    console.log("drag end");
  };
  return (
    <DragDropContext onDragEnd={onDragEnd}>
      <div className="flex gap-2">
        {statusOptions.map(({ type, color }) => {
          const groupedTasks: Task[] = tasks?.filter(
            (task: Task) => task.status === type,
          );
          return (
            <KanbarCard
              key={type}
              name={type}
              color={color}
              tasks={groupedTasks}
            />
          );
        })}
      </div>
    </DragDropContext>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-black/10 px-10 py-3 font-semibold text-slate-200 no-underline transition hover:bg-black/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
